import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="index-container">
        <section className="section-even"></section>
        <section className="section-odd"></section>
        <section className="section-even"></section>
      </Container>
    </>
  );
};

export default Home;
